services:
  - type: web
    name: fingerprint-comparison
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120

    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    healthCheckPath: /
    autoDeploy: true 