services:
  - type: web
    name: fingerprint-matcher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_flask:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: MAX_IMAGE_SIZE
        value: 8388608
      - key: DATA_DIR
        value: /tmp/data
    healthCheckPath: /
    autoDeploy: true 