services:
  - type: web
    name: fingerprint-matching
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p uploads results
    startCommand: gunicorn app:app --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1 